### ISSUE TITLE
Segmentation fault when running test application

### ISSUE THREAD

**Issue by JetmirH** [tuiTelematik/DPDK-WiFi#4]
Hi, 
I am trying to make use of DPDK withath10k support. I have compiled the project using the meson script provided. I run the test application as follows:

sudo ./dpdk-test-ath10k -c 0x1 -n 4 -d ../../drivers/librte_mempool_ring.so 

but it fails to run as it gives a segmentation fault in:  

#0  0x00007ffff74d1f83 in rte_wifi_mgmt_callback_register () from ../../lib/librte_wifi.so.2
#1  0x0000000000400e75 in main ()

If i comment out the rte_wifi_mgmt_callback_register in the test application then it runs and the output is as follows:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
EAL: Detected 2 lcore(s)
TEST1EAL: Probing VFIO support...
EAL: VFIO support initialized
[New Thread 0x7ffff64c6700 (LWP 8941)]
[New Thread 0x7ffff5cc5700 (LWP 8942)]
[New Thread 0x7fff735ff700 (LWP 8943)]

What might be the reason for the first segmentation fault, and what should I expect as an output from the test program?

Thanks in advance!
Jetmir

**Comment by thillux** [comment]
ath10k uses 32-bit descriptor addresses, please only run on a native 32-bit system (without virtualization and so on)
